const Images = {
  HitHouselogo: require('@assets/RecordbookLogoWhite.png'),
  mail: require('@assets/mail.png'),
  night_star: require('@assets/blue_icon_night.png'),
  undraw_check_boxes: require('@assets/undraw_check_boxes.png'),
  calendar: require('@assets/calendar.png'),
  calendar_red: require('@assets/calendar_red.png'),
  calendarPink: require('@assets/calendarPink.png'),
  profile: require('@assets/profile.png'),
  browse: require('@assets/browse.png'),
  support: require('@assets/support.png'),
  support_red: require('@assets/support_red.png'),
  searchRed: require('@assets/searchRed.png'),
  searchBlue: require('@assets/searchBlue.png'),
  user: require('@assets/user.png'),
  user_red: require('@assets/user_red.png'),
  user_gear: require('@assets/user_gear.png'),
  chat: require('@assets/chat.png'),
  celebration: require('@assets/celebration.png'),
  add: require('@assets/add.png'),
  add_red: require('@assets/add_red.png'),
  dubbing: require('@assets/dubbing.png'),
  dubbing_red: require('@assets/dubbing_red.png'),
  i_Icon: require('@assets/i_icon.png'),
  signBG: require('@assets/signInBG.png'),
  signBGBlur: require('@assets/signInBGBlur.png'),
  email: require('@assets/email.png'),
  instagram: require('@assets/instagram.png'),
  lock: require('@assets/lock.png'),
  image: require('@assets/image.png'),
  exampleImage: require('@assets/ExampleImage.png'),
  calendar_tab_ic: require('@assets/calendar_tab_ic.png'),
  search_tab_ic: require('@assets/search_tab_ic.png'),
  profile_tab_ic: require('@assets/profile_tab_ic.png'),
  calendar_tab_inactive_ic: require('@assets/calendar_tab_inactive_ic.png'),
  search_tab_inactive_ic: require('@assets/search_tab_inactive_ic.png'),
  profile_tab_inactive_ic: require('@assets/profile_tab_inactive_ic.png'),
};

export default Images;
