require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
$RNFirebaseAsStaticFramework = true
target 'RecordBook' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://github.com/berbix/berbix-ios-spec.git'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper' => '0.80.0' })
  #use_flipper!()
  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })


  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

target 'RecordBookTests' do
  inherit! :complete
  # Pods for testing1
end

end

target 'RecordBook-tvOS' do
  # Pods for RecordBook-tvOS

  target 'RecordBook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
